website/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin


from website.core import views
from website.core.forms import BuscaForm

urlpatterns = [
    url('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),
    path('sobre/', views.sobre, name='sobre'),
    path('busca/', views.Busca, name='busca', kwargs={'form': BuscaForm}),
    url('contato/$', views.contato, name='contato'),
    path('detalhes/<str:id_imovel>', views.detalhes, name='detalhes'),
    path('lista/<str:tipo_imovel>/<str:categoria_imovel>', views.lista, name='lista'),
    path('todos/', views.todos, name='todos'),
    path('telao1/', views.telao1, name='telao1'),
    path('telao2/', views.telao2, name='telao2'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = 'Imobiliária'
admin.site.site_header = 'Nome Imobiliaria'
admin.site.index_title = 'Painel de administração'

website/core/models.py
import uuid
import re

from cloudinary.models import CloudinaryField
from django.db import models
from geopy import geocoders

UF_CHOICES = (
    ('RS', 'Rio Grande do Sul'),
    ('SC', 'Santa Catarina')
)


class Categoria(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    descricao = models.CharField('categoria casa, apartamento, etc', max_length=50)

    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'
        db_table = 'categoria'


class Cidade(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nome = models.CharField('nome', max_length=50)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'cidade'
        verbose_name_plural = 'cidades'
        db_table = 'cidade'


class Bairro(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nome = models.CharField('nome', max_length=50)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'bairro'
        verbose_name_plural = 'bairros'
        db_table = 'bairro'
        ordering = ('nome',)


class Tipo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tipo = models.CharField('tipo venda ou locação', max_length=50)

    def __str__(self):
        return self.tipo

    class Meta:
        verbose_name = 'tipo'
        verbose_name_plural = 'tipos'
        db_table = 'tipo'


class Imovel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    data = models.DateField('data do anúncio')
    preco = models.DecimalField('valor', decimal_places=2, max_digits=15)
    endereco = models.CharField('endereço', max_length=300, blank=True, null=True)
    codigo = models.CharField('código imóvel', max_length=10, blank=True)
    numero = models.CharField('número', max_length=20, blank=True)
    bairro = models.ForeignKey(Bairro, on_delete=models.PROTECT, null=True)
    cidade = models.ForeignKey(Cidade, on_delete=models.PROTECT, null=True)
    uf = models.CharField('uf', max_length=2, choices=UF_CHOICES, blank=True, null=True)
    quartos = models.PositiveSmallIntegerField('dormitórios', default=0)
    suites = models.PositiveSmallIntegerField('suítes', default=0)
    salaofesta = models.PositiveSmallIntegerField('Salão de festas', default=0, blank=True)
    sala = models.PositiveSmallIntegerField('Sala de estar', default=0)
    salajantar = models.PositiveSmallIntegerField('Sala de jantar', default=0)
    cozinha = models.PositiveSmallIntegerField('Cozinha', default=0)
    churrasqueira = models.PositiveSmallIntegerField('Churrasqueira', default=0, blank=True)
    areaservico = models.PositiveSmallIntegerField('Area de serviço', default=0, blank=True)
    metragem_terreno = models.IntegerField('Metragem terreno', default=0)
    metragem_privativo = models.IntegerField('Metragem privativa', default=0)
    garagem = models.PositiveSmallIntegerField('vagas de garagem', default=0)
    banheiro = models.PositiveSmallIntegerField('banheiros', default=0)
    titulo = models.CharField('título', max_length=100)
    descricao = models.TextField('descrição', max_length=5000)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    tipo = models.ForeignKey(Tipo, on_delete=models.PROTECT)
    imagem = CloudinaryField('imagem de capa')
    visivel = models.BooleanField('mostrar no site', default=True)
    dataCobranca = models.CharField('dia de vencimento', blank=True, max_length=2)
    dataVenda = models.DateField('data da venda', blank=True, null=True)
    dataContrato = models.DateField('data de inicio do contrato', blank=True, null=True)
    nome_proprietario = models.CharField('nome do proprietário', max_length=200)
    fone_proprietario = models.CharField('Telefone do proprietário', max_length=200, null=True)
    observacao_proprietario = models.TextField('Observações do proprietário', blank=True)
    latitude = models.CharField('Latitude', max_length=20, blank=True)
    longitude = models.CharField('Longitude', max_length=20, blank=True)
    tarja = models.CharField('Tarja', max_length=300, blank=True, null=True)
    negociavel = models.BooleanField('Valor negociável', default=False)
    troca = models.CharField('Aceita troca por', max_length=300, blank=True, null=True)
    observacoes_internas = models.TextField('Observações internas', blank=True, null=True)
    video = models.CharField('Link do vídeo no Youtube', max_length=100, blank=True)
    cpf_adquirinte = models.CharField('não usado', blank=True, null=True, max_length=100)
    cpf_proprietario = models.CharField('não usado', blank=True, null=True, max_length=100)
    nome_adquirinte = models.CharField('nao usar', null=True, blank=True, max_length=100)
    mensagem_adicional = models.CharField('Mensagem adicional', null=True, blank=True, max_length=300)

    def __str__(self):
        return self.titulo

    def obterEndereco(self):
        if self.bairro and self.cidade and self.uf:
            return f'{self.bairro}, {self.cidade.nome} - {self.uf}'
        else:
            return ''

    def save(self, *args, **kwargs):
        try:
            g = geocoders.GoogleV3(api_key='AIzaSyByFCKk6PjOLP77cF2YfSrJogdDPYc2zug')
            input_address = self.obterEndereco()
            location = g.geocode(input_address, timeout=10)
            self.latitude = location.latitude
            self.longitude = location.longitude
        except Exception as e:
            print(e)
        try:
            super().save(*args, **kwargs)
        except Exception as e:
            print(e)

    def video_id(self):
        regex = re.compile(
            r'(https?://)?(www\.)?(youtube|youtu|youtube-nocookie)\.(com|be)/(watch\?v=|embed/|v/|.+\?v=)?(?P<id>[A-Za-z0-9\-=_]{11})')
        match = regex.match(self.video)
        video = match.group('id')
        return video

    class Meta:
        verbose_name = 'imóvel'
        verbose_name_plural = 'imóveis'
        db_table = 'imovel'


class ImagemImovel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    imagem = CloudinaryField('imagem de capa')
    imovel = models.ForeignKey(Imovel, verbose_name='imovel', on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'imagem'
        verbose_name_plural = 'imagens'


class Interessados(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nome = models.CharField('nome', max_length=100)
    email = models.CharField('e-mail', max_length=100)
    telefone = models.CharField('telefone', max_length=100)
    imovel = models.ForeignKey(Imovel, verbose_name='imóvel', on_delete=models.PROTECT)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Interessados'
        verbose_name_plural = 'Interessados'


class Contato(models.Model):
    nome = models.CharField(max_length=100)
    telefone = models.CharField(blank=True, max_length=20)
    email = models.EmailField(blank=True, max_length=100)
    mensagem = models.TextField()

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Contatos'
        verbose_name_plural = 'Contatos'


class Institucional(models.Model):
    whatsapp = models.CharField('whatsapp principal', max_length=100)
    whatsappsecundario = models.CharField('whatsapp secundário', max_length=100)
    mensagem_imovel = models.CharField('mensagem adicional no imóvel', max_length=300, null=True, blank=True)

    def __str__(self):
        return self.whatsapp

    class Meta:
        verbose_name = 'institucional'
        verbose_name_plural = 'institucional'


class Banner(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nome = models.CharField(max_length=100)
    texto = models.CharField(max_length=500, null=True, blank=True)
    imagem = CloudinaryField('imagem de capa')
    url = models.URLField('Link', blank=True, null=True)
    celular = models.BooleanField('Versão para celular', blank=True, default=False)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Banner'
        verbose_name_plural = 'Banners'

website/core/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.generic import TemplateView

from website.core.forms import ContatoForm, BuscaForm, ContatoImovelForm, BuscaCodigoForm
from website.core.models import Imovel, Categoria, Tipo, Interessados, Contato, Banner, Institucional


class Home(TemplateView):

    def get(self, request, *args, **kwargs):
        form = BuscaForm(data=request.POST or None)
        form_codigo = BuscaCodigoForm(data=request.POST or None)
        imoveis = Imovel.objects.filter(visivel=True).order_by("-data")[:8]
        categorias = Categoria.objects.all()
        tipos = Tipo.objects.all()
        institucional, _ = Institucional.objects.get_or_create(pk=1)
        banners_cell = Banner.objects.all().filter(celular=True)
        banners_desk = Banner.objects.all().filter(celular=False)
        return render(request, 'core/index.html',
                      {'imoveis': imoveis, 'categorias': categorias, 'tipos': tipos, 'form': form,
                       'form_codigo': form_codigo,
                       'banner_cell': banners_cell, 'banner_desk': banners_desk, 'institucional': institucional})

    def post(self, request):
        institucional, _ = Institucional.objects.get_or_create(pk=1)
        form = BuscaForm(data=request.POST or None)
        form_codigo = BuscaCodigoForm(data=request.POST or None)
        imoveis = Imovel.objects.filter(visivel=True).order_by("-data")[:8]
        categorias = Categoria.objects.all()
        tipos = Tipo.objects.all()
        if form.is_valid():
            tipo_f = request.POST.get('tipo')
            categoria_f = request.POST.get('categoria')
            cidade_f = request.POST.get('cidade')
            bairro_f = request.POST.get('bairro')
            preco_ff = request.POST.get('preco')

            if 'todos' == bairro_f or 'Todos' == bairro_f:
                imoveis = Imovel.objects.filter(tipo=tipo_f).filter(categoria=categoria_f).filter(
                    cidade=cidade_f).filter(visivel=True)
            else:
                imoveis = Imovel.objects.filter(tipo=tipo_f).filter(categoria=categoria_f).filter(
                    cidade=cidade_f).filter(bairro=bairro_f).filter(visivel=True)

            if preco_ff == 'acima':
                imoveis = imoveis.filter(preco__range=(600000, 99999999)).filter(visivel=True)
            elif preco_ff == 'todos' or preco_ff == 'Qualquer valor':
                imoveis = imoveis
            else:
                imoveis = imoveis.filter(preco__range=(0, preco_ff)).filter(visivel=True)
            return render(request, 'core/index.html',
                          {'imoveis': imoveis, 'categorias': categorias, 'tipos': tipos, 'form': form,
                           'form_codigo': form_codigo,
                           'institucional': institucional})
        else:
            pass
        if form_codigo.is_valid():
            codigo = request.POST.get('codigo')
            imoveis = Imovel.objects.filter(codigo=codigo).filter(visivel=True)

        return render(request, 'core/index.html',
                      {'imoveis': imoveis, 'categorias': categorias, 'tipos': tipos, 'form': form,
                       'form_codigo': form_codigo,
                       'institucional': institucional})


def sobre(request):
    institucional, _ = Institucional.objects.get_or_create(pk=1)
    categorias = Categoria.objects.all()
    tipos = Tipo.objects.all()
    return render(request, 'core/sobre.html',
                  {'categorias': categorias, 'tipos': tipos, 'institucional': institucional})


def contato(request):
    institucional, _ = Institucional.objects.get_or_create(pk=1)
    form_class = ContatoForm
    categorias = Categoria.objects.all()
    tipos = Tipo.objects.all()
    if request.method == 'GET':
        return render(request, 'core/contato.html', {
            'categorias': categorias,
            'tipos': tipos,
            'form': form_class, 'institucional': institucional
        })

    if request.method == 'POST':
        nome = request.POST.get('nome', '')
        email = request.POST.get('email', '')
        telefone = request.POST.get('telefone', '')
        mensagem = request.POST.get('mensagem', '')

        c = Contato.objects.create(nome=nome, email=email, telefone=telefone, mensagem=mensagem)
        c.save()

        return redirect('contato')


def detalhes(request, id_imovel):
    institucional, _ = Institucional.objects.get_or_create(pk=1)
    form_class = ContatoImovelForm(initial={'id_imovel': id_imovel})
    if request.method == 'GET':
        imovelSelecionado = Imovel.objects.get(id=id_imovel)
        categorias = Categoria.objects.all()
        tipos = Tipo.objects.all()
        return render(request, 'core/detalhes.html',
                      {
                          'imovel': imovelSelecionado,
                          'categorias': categorias,
                          'tipos': tipos,
                          'lat': imovelSelecionado.latitude,
                          'long': imovelSelecionado.longitude,
                          'form': form_class, 'institucional': institucional
                      })
    if request.method == 'POST':
        id = request.POST.get('id_imovel', '')

        imv = Imovel.objects.get(id=id)
        nome = request.POST.get('nome', '')
        email = request.POST.get('email', '')
        telefone = request.POST.get('telefone', '')

        i = Interessados.objects.create(nome=nome, email=email, telefone=telefone, imovel=imv)
        i.save()

        return redirect('detalhes', imv.id)


def lista(request, tipo_imovel, categoria_imovel):
    institucional, _ = Institucional.objects.get_or_create(pk=1)
    tipos = Tipo.objects.get(id=tipo_imovel)
    categorias = Categoria.objects.get(id=categoria_imovel)
    imoveis = Imovel.objects.filter(tipo=tipos, categoria=categorias, visivel=True)
    categorias_lista = Categoria.objects.all()
    tipos_lista = Tipo.objects.all()
    return render(request, 'core/lista.html',
                  {'imoveis': imoveis,
                   'categorias': categorias_lista,
                   'tipos': tipos_lista, 'institucional': institucional})


def Busca(request, *args, **kwargs):
    institucional, _ = Institucional.objects.get_or_create(pk=1)
    if request.method == 'GET':
        form = BuscaForm
        return render(request, 'core/busca.html', {'form': form, 'institucional': institucional})
    if request.method == 'POST':
        return render(request, 'core/busca.html')


def todos(request):
    institucional, _ = Institucional.objects.get_or_create(pk=1)
    imoveis = Imovel.objects.filter(visivel=True).order_by("-data")
    categorias_lista = Categoria.objects.all()
    tipos_lista = Tipo.objects.all()
    return render(request, 'core/lista.html',
                  {'imoveis': imoveis,
                   'categorias': categorias_lista,
                   'tipos': tipos_lista, 'institucional': institucional})


def telao1(request):
    imoveis = Imovel.objects.filter(visivel=True).order_by("-data")[:10]
    return render(request, 'core/telao1.html', {'imoveis': imoveis})


def telao2(request):
    imoveis = Imovel.objects.filter(visivel=True).order_by("-data")[:10]
    return render(request, 'core/telao2.html', {'imoveis': imoveis})

website/core/templates/core/busca.html
{% extends 'base.html' %}
{% block content %}
    <div class="sessao1">
        {% for imovel in imoveis %}
            <div class="col-md-4">
                <div class="destaques-col3">
                    <section>
                        <a href="{% url 'detalhes' imovel.id %}" title="{{ imovel.titulo }}">
                            <img src="http://res.cloudinary.com/hfrhkgogi/image/upload/c_scale,w_300,q_80/v1528977020/{{ imovel.imagem }}.jpg" alt="{{ imovel.titulo }}" width="100%"/>
                        </a>
                        <h5>{{ imovel.tipo.tipo }}</h5>
                        <h4>R$ {{ imovel.preco }}</h4>
                        <p style="min-height: 50px">{{ imovel.endereco }}, {{ imovel.numero }}, {{ imovel.cep }} {{ imovel.cidade }} {{ imovel.estado }}</p>
                        <hr/>
                        <span>
                            {% if imovel.quartos > 0 %}
                            <p><i class="fas fa-bed"></i><strong>{{ imovel.quartos }}</strong> quartos</p>
                            {% endif %}
                            <p><i class="fas fa-car"></i><strong>{{ imovel.garagem }}</strong> vagas</p>
                            {% if imovel.banheiro > 0 %}
                            <p><i class="fas fa-bath"></i><strong>{{ imovel.banheiro }}</strong> banheiros</p>
                            {% endif %}
                        </span>
                        <hr/>
                        <a href="{% url 'detalhes' imovel.id %}" class="link">ver detalhes</a>
                    </section>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

website/core/templates/core/contato.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
    <div class="container">
        <div class="sessao1">
            <div class="row">
                <div class="col-md-6">
                    <h2 style="font-weight: 500">Contato</h2>
                    <p>
                        Ficou com alguma dúvida?
                        preencha o formulário ao lado, que entraremos em contato assim que possível.
                    </p>
                </div>
                <div class="col-md-6">
                    <form role="form" action="" method="post" style="font-weight: 400">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">
                                Enviar
                            </button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/core/templates/core/detalhes.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load l10n %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
    <style>

        .slides {
            margin: 0 10px;
        }

        .slides span {
            padding: 2px;
            margin: 5px;
            box-shadow: 0 0 10px #c0c0c0;
            width: 22%;
        }

        #imagemPrincipal {
            padding: 2px;
            box-shadow: 0 0 10px #c0c0c0;
        }

        i {
            margin-right: 10px;
        }

        #map {
            height: 400px;
            width: 100%;
        }
    </style>
    <div class="container">
        <div class="sessao1">
            <h2>{{ imovel.titulo }}</h2>
            <hr/>
            <h5>
                <small class="h6 text-muted mr-5">Cód: {{ imovel.codigo }}</small>
                imóvel para {{ imovel.tipo }}
            </h5>
            <div class="row mt-5">
                <div class="col-md-6 mt-2">
                    <div id="carouselExampleControls" class="carousel slide card py-5" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <a href="http://res.cloudinary.com/hfrhkgogi/image/upload/c_scale,q_85/v1528977020/{{ imovel.imagem }}.jpg"
                                   target="_blank">
                                    <img id="imagemPrincipal"
                                         src="http://res.cloudinary.com/hfrhkgogi/image/upload/c_scale,w_500,q_80/v1528977020/{{ imovel.imagem }}.jpg"
                                         class="d-block w-100"/>
                                </a>
                            </div>
                            {% for ii in imovel.imagemimovel_set.select_related %}
                                <div class="carousel-item">
                                    <a href="http://res.cloudinary.com/hfrhkgogi/image/upload/c_scale,q_85/v1528977020/{{ ii.imagem }}.jpg"
                                       target="_blank">
                                        <img id="imagemPrincipal"
                                             src="http://res.cloudinary.com/hfrhkgogi/image/upload/c_scale,w_500,q_80/v1528977020/{{ ii.imagem }}.jpg"
                                             class="d-block w-100"/>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button"
                           data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button"
                           data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    {% if imovel.tarja %}
                        <h5 class="text-white p-1 m-0 px-2 bg-primary"
                            style="position: absolute; top:30px;">{{ imovel.tarja }}</h5>
                    {% endif %}
                    <div class="card mt-4">
                        <h5 class="card-header">Entre em contato</h5>
                        <div class="card-body">
                            <p>Ficou interessado neste imóvel? Fale com nossos corretores.</p>
                            <form role="form" action="" method="post">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% buttons %}
                                    <button type="submit" class="btn btn-primary">
                                        Enviar
                                    </button>
                                {% endbuttons %}
                            </form>
                            <p>Telefone e whatsapp:</p>
                            <p style="font-size: 1.2em;">
                                <i class="fas fa-phone-square text-primary fa-2x"></i> (49) 3444 1966
                                <br>
                                {% if institucional.whatsapp %}
                                    <a href="http://api.whatsapp.com/send?1=pt_BR&amp;phone=55{{ institucional.whatsapp }}"
                                       class="text-dark">
                                        <i class="fab fa-whatsapp-square text-success fa-2x"></i> {{ institucional.whatsapp }}
                                    </a>
                                    <br>
                                {% endif %}
                                {% if institucional.whatsappsecundario %}
                                    <a href="http://api.whatsapp.com/send?1=pt_BR&amp;phone=55{{ institucional.whatsappsecundario }}"
                                       class="text-dark">
                                        <i class="fab fa-whatsapp-square text-success fa-2x"></i> {{ institucional.whatsappsecundario }}
                                    </a>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 mt-2">
                    <section class="card">
                        <h5 class="card-header">Detalhes</h5>
                        <div class="card-body">
                            {% if imovel.quartos > 0 %}
                                <p><i class="fas fa-bed"></i><strong>{{ imovel.quartos }}</strong> dormitórios</p>
                            {% endif %}
                            {% if imovel.suites > 0 %}
                                <p><i class="fas fa-bed"></i><strong>{{ imovel.suites }}</strong> suítes</p>
                            {% endif %}
                            {% if imovel.banheiro %}
                                <p><i class="fas fa-bath"></i><strong>{{ imovel.banheiro }}</strong> banheiros</p>
                            {% endif %}
                            {% if imovel.cozinha %}
                                <p><i class="fas fa-utensils"></i><strong>{{ imovel.cozinha }}</strong> cozinha</p>
                            {% endif %}
                            {% if imovel.sala %}
                                <p><i class="fas fa-square"></i><strong>{{ imovel.sala }}</strong> sala de estar</p>
                            {% endif %}
                            {% if imovel.salajantar %}
                                <p><i class="fas fa-utensils"></i><strong>{{ imovel.salajantar }}</strong> sala de
                                    jantar</p>
                            {% endif %}
                            {% if imovel.areaservico %}
                                <p><i class="fas fa-th-large"></i><strong>{{ imovel.areaservico }}</strong> área de
                                    serviço</p>
                            {% endif %}
                            {% if imovel.salaofesta %}
                                <p><i class="fas fa-glass-cheers"></i><strong>{{ imovel.salaofesta }}</strong> salão de
                                    festas</p>
                            {% endif %}
                            {% if imovel.churrasqueira %}
                                <p><i class="fas fa-drumstick-bite"></i><strong>{{ imovel.churrasqueira }}</strong>
                                    churrasqueira</p>
                            {% endif %}
                            {% if imovel.garagem %}
                                <p><i class="fas fa-car"></i><strong>{{ imovel.garagem }}</strong> vagas</p>
                            {% endif %}
                            {% if imovel.metragem_privativo %}
                                <p><i class="fas fa-vector-square"></i>Área privativa
                                    <strong>{{ imovel.metragem_privativo }} m²</strong>
                                </p>
                            {% endif %}
                            {% if imovel.metragem_terreno %}
                                <p><i class="fas fa-vector-square"></i>Área do terreno
                                    <strong>{{ imovel.metragem_terreno }}
                                        m²</strong>
                                </p>
                            {% endif %}
                            {% if imovel.obterEndereco %}
                                <p>
                                <h5>Endereço</h5>
                                <i class="fas fa-map-marker-alt"></i>{{ imovel.obterEndereco }}
                                </p>
                            {% endif %}
                            <br>
                            <h5>Descrição</h5>
                            {{ imovel.descricao|linebreaks }}
                            </p>
                            <br>
                            {% if imovel.preco == 0 %}
                                <h5>R$: Consulte-nos</h5>
                            {% else %}
                                <h5>R$ {{ imovel.preco }}</h5>
                            {% endif %}
                            {% if institucional.mensagem_imovel %}
                                <p>{{ institucional.mensagem_imovel }}</p>
                            {% endif %}
                            {% if imovel.mensagem_adicional %}
                                <p>{{ imovel.mensagem_adicional }}</p>
                            {% endif %}
                            {% if imovel.negociavel %}
                                <h6>Valor negociável</h6>
                            {% endif %}
                            {% if imovel.troca %}
                                <p>Aceita na negociação {{ imovel.troca }}</p>
                            {% endif %}
                        </div>
                    </section>
                    {% if imovel.video %}
                        <div class="card mt-4">
                            <h5 class="card-header">Veja o vídeo</h5>
                            <div class="card-body">
                                <iframe width="100%" height="315"
                                        src="https://www.youtube.com/embed/{{ imovel.video_id }}"
                                        frameborder="0"
                                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                        allowfullscreen></iframe>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


    <script>
        function trocarImagem(caminho) {
            document.getElementById("imagemPrincipal").src = caminho;
        }

    </script>

{% endblock %}

website/core/templates/core/index.html
{% extends 'base.html' %}
{% block content %}
    {% include 'includes/carousel.html' %}
    {% include 'includes/busca.html' %}
    <div class="container" style="margin: 50px auto">
        <h2>Imóveis em destaque</h2>
        <div class="row">
            {% for imovel in imoveis %}
                {% include 'includes/item-imovel.html' %}
            {% empty %}
                <h4 class="mx-5">Nenhum imóvel localizado</h4>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col offset-11">
                <a href="{% url 'todos' %}" class="btn btn-primary my-5">Ver todos</a>
            </div>
        </div>
    </div>
{% endblock %}

website/core/templates/core/lista.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Imóveis</h2>
        <div class="row">
            {% for imovel in imoveis %}
                {% include 'includes/item-imovel.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}